name: Node.js CI
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version
          
  Installing_pm2_and_deploy_application:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: PM2 installation & Verify
        run: |
            sudo npm install -g pm2
            pm2 --version || true
     
      
#       - name: Start application with PM2
#         run: |
#            cd /home/ubuntu/actions-runner/_work/Node_js_Application/Node_js_Application
#            pm2 start index.js
#       - name: Stop application with PM2
#         run: |
#           pm2 stop all || true
      - name: Start application with PM2
        run: |
          cd /home/ubuntu/actions-runner/_work/Node_js_Application/Node_js_Application
          pm2 start index.js --name "my-app"
          pm2 status
          pm2 logs
          
#       - name: Restart application with PM2
#         run: |
#            pwd
#            cd /home/ubuntu/actions-runner/_work/Node_js_Application/Node_js_Application
#            pm2 stop all || true
#            pm2 restart my-app &
#            pm2 status
#            pm2 logs
